language: go

# S: Build Lifecycle
install:
  - go get github.com/InkProject/ink
  # - ink build $GOPATH/src/github.com/InkProject/ink/template
  - ink build
# before_script

script:
  - cd ./docs
  - git init
  - git config user.name "猎暄同学"
  - git config user.email "alan.gui@foxmail.com"
  - git add .
  - git commit -m "update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# after-script:
# E: Build Lifecycle

branches:
  only:
    - blog-source
env:
  global:
    - GH_REF: github.com/ZhaoGui/beilinblog
