site:
    title: "北林有涧"
    subtitle: "寤寐独歌"
    limit: 10
    theme: dark
    lang: zh
    url: "http://www.chole.io/blog"
    comment: username
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    root: "/blog"

authors:
    me:
        name: "猎暄同学"
        intro: "和自己喜欢的一切在一起"
        avatar: "-/images/avatar.png"

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "README.md"
    # Excuted command when use 'ink publish'
    publish: |
        git add .
        git commit -m "update"
        git push origin blog-source
